backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "categories"
    label: "Categories"
    folder: "src/categories"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Title (zh)", name: "title_zh", widget: "string"}
  - name: "tabs"
    label: "Tabs"
    folder: "src/tabs"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Title (zh)", name: "title_zh", widget: "string"}
      - {label: "Content", name: "content", widget: "markdown"}
      - {label: "Content (zh)", name: "content_zh", widget: "markdown"}
      - {label: "URL", name: "url", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
  - name: "talking_points"
    label: "Talking points"
    folder: "src/talking_points"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Title (zh)", name: "title_zh", widget: "string"}
      - {label: "Rebuttal", name: "rebuttal", widget: "markdown"}
      - {label: "Rebuttal (zh)", name: "rebuttal_zh", widget: "markdown"}
      - {label: "Background Image URL", name: "background_image_url", widget: "string", required: false}
      - label: "Background image alignment"
        name: "background_image_alignment"
        widget: "select"
        options:
          - "right"
          - "bottom"
        default: "right"
        required: false
      - {label: "Ask Yourself Text", name: "ask_yourself", widget: "markdown", required: false}
      - {label: "Ask Yourself Text (zh)", name: "ask_yourself_zh", widget: "markdown", required: false}
      - label: "Category"
        name: "category"
        widget: "relation"
        collection: "categories"
        valueField: "title"
        searchFields: ["title", "title_zh"]
      - label: "Color"
        name: "color"
        widget: "select"
        default: '#8A5413'
        options:
          - '#1F0E03'
          - '#331707'
          - '#462009'
          - '#58280B'
          - '#7A370F'
          - '#8A5413'
          - '#B57033'
          - '#BF8149'
          - '#E29C5E'
          - '#F7B77D'
      - label: "Read more links"
        name: "read_more"
        widget: "list"
        required: false
        summary: '{{fields.link_title}}'
        fields:
          - {label: "URL", name: "url", widget: "string"}
          - {label: "Link title", name: "link_title", widget: "string"}
          - {label: "Source", name: "source", widget: "string"}
          - {label: "Image URL", name: "image_url", widget: "string", required: false}
