backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "talking_points"
    identifier_field: id
    label: "Talking points"
    folder: "src/talking_points"
    create: true
    fields:
      - {label: "Id", name: "id", widget: "string"}
      - {label: "Title (en)", name: "title_en", widget: "markdown"}
      - {label: "Title (zh)", name: "title_zh", widget: "markdown"}
      - {label: "Rebuttal (en)", name: "rebuttal_en", widget: "markdown"}
      - {label: "Rebuttal (zh)", name: "rebuttal_zh", widget: "markdown"}
